- name: Configure web server
  hosts: web_servers
  become: true
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: latest
      become: true

    - name: Start Apache
      service:
        name: httpd
        state: started

    - name: Install mod_ssl
      yum:
        name: mod_ssl
        state: latest
      become: true

    - name: Configure SSL certificates
      copy:
        src: /path/to/ssl/certificates
        dest: /etc/httpd/conf.d/
        owner: root
        group: root
        mode: 0644
      become: true

    - name: Configure firewall
      firewalld:
        service: http
        state: enabled
        immediate: true
